### ISSUE TITLE
Add 'meta' property to APIs

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/orgs-model#47]
## Overview

Depends on [updates to the `federated-json` package`](https://github.com/liquid-labs/federated-json/issues/5).

In order to better support downstream use cases, let's provide some self-awareness to the APIs.

## Deliverables

* [ ] Move the `key` property to `meta.key`.
* [ ] Add `meta.fields` which is something like `{ field1: { required: true }` where `required` can be `true`, `false`, or `'CONDITIONAL'`.
* [ ] Add `meta.schema` which returns the schema for the fragment.
